# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Genericproductnew' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'genericproductnew' do
    @driver.get('https://www.relayduty.com/company/products')
    @driver.find_element(:link_text, 'New Generic Product').click
    @driver.find_element(:id, 'company_product_prod_code').send_keys('productid1')
    @driver.find_element(:id, 'company_product_prod_title').send_keys('cake and cookies')
    @driver.find_element(:id, 'company_product_product_family').send_keys('cake and cookies')
    @driver.find_element(:id, 'company_product_product_group').send_keys('M2')
    @driver.find_element(:id, 'company_product_gross_weight').send_keys('10')
    @driver.find_element(:id, 'company_product_volumn').send_keys('10')
    @driver.find_element(:css, '#select2-company_product_unit-container > .select2-selection__placeholder').click
    @driver.find_element(:css, '#select2-company_product_currency-container > .select2-selection__placeholder').click
    @driver.find_element(:css, '.row:nth-child(2) > .col-md-6:nth-child(2) > .row:nth-child(5) > .col-md-4').click
    @driver.find_element(:css, '#select2-company_product_vendor_country-container > .select2-selection__placeholder').click
    @driver.find_element(:id, 'company_product_customer_reff').send_keys('1')
    @driver.find_element(:css, '.select2-search__field').send_keys('10063061')
    @driver.find_element(:id, 'company_product_initial_tariff').send_keys('2369.80.00')
    @driver.find_element(:css, '#select2-company_product_custom_origin-container > .select2-selection__placeholder').click
    @driver.find_element(:id, 'company_product_additional_code1').send_keys('1001')
    @driver.find_element(:id, 'company_product_additional_code2').send_keys('1001')
    @driver.find_element(:id, 'company_product_custom_description').send_keys('1001')
    @driver.find_element(:id, 'company_product_item_name').send_keys('Pinata 3D cake')
    @driver.find_element(:id, 'company_product_main_characteristic1').send_keys('Flower + Barbie doll theme ')
    @driver.find_element(:id, 'company_product_main_characteristic2').send_keys('machine')
    @driver.find_element(:id, 'company_product_main_characteristic2').send_keys('machine design')
    @driver.find_element(:id, 'company_product_main_component1').send_keys('land')
    @driver.find_element(:id, 'company_product_main_component1').send_keys('land + table')
    @driver.find_element(:css, '.row:nth-child(4) > .col-md-6:nth-child(2) > .row:nth-child(5) > .col-md-4').click
    @driver.find_element(:id, 'company_product_main_component2').send_keys('government land ')
    @driver.find_element(:id, 'company_product_main_usage1').send_keys('to fix product')
    @driver.find_element(:xpath, '//*[@id=\"new_product_management\"]/form/div/div[5]/button/span').click
  end
end
