# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Genericproductsearch' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'genericproductsearch' do
    @driver.get('https://www.relayduty.com/company/products')
    @driver.find_element(:id, 'prod_title').send_keys('TAP collection')
    @driver.find_element(:id, 'product_family').send_keys('TAP collection')
    @driver.find_element(:id, 'tariff_code_eu').send_keys('2105.00.10.00')
    @driver.find_element(:id, 'custom_origin').send_keys('South Africa')
    @driver.find_element(:name, 'commit').click
  end
end
