# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Genericproductdestroy' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'genericproductdestroy' do
    @driver.get('https://www.relayduty.com/company/products')
    @driver.find_element(:css, '.ID-78467745-ffc9-4cab-8102-f0378a37457c .btn-group > .btn').click
    @driver.find_element(:link_text, 'Delete Product').click
    @driver.find_element(:css, '.ajs-ok').click
  end
end
