# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'GenericproductEdit' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'genericproductEdit' do
    @driver.get('https://www.relayduty.com/company/products')
    @driver.find_element(:css, '.ID-0696be3a-0392-4347-94d3-484ec4c72adf .btn-group > .btn').click
    @driver.find_element(:link_text, 'Edit Product').click
    @driver.find_element(:id, 'company_product_item_name').click
    @driver.find_element(:id, 'company_product_item_name').send_keys('Pinata 3D cake and solution')
    @driver.find_element(:css, '.product-btn').click
  end
end
